spring:
  application:
    name: acadia
  main:
    web-application-type: reactive
  output:
    ansi:
      enabled: always
management:
  endpoints:
    web:
      exposure:
        include: health,gateway
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
