spring:
  application:
    name: acadia
  main:
    web-application-type: reactive
  output:
    ansi:
      enabled: always
  cloud:
    gateway:
      server:
        webflux:
          httpclient:
            response-timeout: 3s
management:
  endpoints:
    web:
      exposure:
        include: health,gateway
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

user-service:
  url: http://localhost:8081

order-service:
  url: http://localhost:8082
